/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../core';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BackupRestoreResponse } from '../models';
// @ts-ignore
import type { MiddlewaresPermissionDenied } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * SystemRestoreApi - axios parameter creator
 * @export
 */
export const SystemRestoreApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Upload JSON or gzip-compressed (.json.gz) backup of ocserv groups
         * @summary Restore ocserv groups
         * @param {string} authorization Bearer TOKEN
         * @param {File} file JSON or JSON.GZ file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservGroupsPost: async (authorization: string, file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('backupOcservGroupsPost', 'authorization', authorization)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('backupOcservGroupsPost', 'file', file)
            const localVarPath = `/backup/ocserv_groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload JSON or gzip-compressed (.json.gz) backup of ocserv users
         * @summary Restore ocserv users
         * @param {string} authorization Bearer TOKEN
         * @param {File} file JSON or JSON.GZ file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservUsersPost: async (authorization: string, file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('backupOcservUsersPost', 'authorization', authorization)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('backupOcservUsersPost', 'file', file)
            const localVarPath = `/backup/ocserv_users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemRestoreApi - functional programming interface
 * @export
 */
export const SystemRestoreApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemRestoreApiAxiosParamCreator(configuration)
    return {
        /**
         * Upload JSON or gzip-compressed (.json.gz) backup of ocserv groups
         * @summary Restore ocserv groups
         * @param {string} authorization Bearer TOKEN
         * @param {File} file JSON or JSON.GZ file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async backupOcservGroupsPost(authorization: string, file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BackupRestoreResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.backupOcservGroupsPost(authorization, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemRestoreApi.backupOcservGroupsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Upload JSON or gzip-compressed (.json.gz) backup of ocserv users
         * @summary Restore ocserv users
         * @param {string} authorization Bearer TOKEN
         * @param {File} file JSON or JSON.GZ file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async backupOcservUsersPost(authorization: string, file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BackupRestoreResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.backupOcservUsersPost(authorization, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemRestoreApi.backupOcservUsersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemRestoreApi - factory interface
 * @export
 */
export const SystemRestoreApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemRestoreApiFp(configuration)
    return {
        /**
         * Upload JSON or gzip-compressed (.json.gz) backup of ocserv groups
         * @summary Restore ocserv groups
         * @param {SystemRestoreApiBackupOcservGroupsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservGroupsPost(requestParameters: SystemRestoreApiBackupOcservGroupsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<BackupRestoreResponse> {
            return localVarFp.backupOcservGroupsPost(requestParameters.authorization, requestParameters.file, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload JSON or gzip-compressed (.json.gz) backup of ocserv users
         * @summary Restore ocserv users
         * @param {SystemRestoreApiBackupOcservUsersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservUsersPost(requestParameters: SystemRestoreApiBackupOcservUsersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<BackupRestoreResponse> {
            return localVarFp.backupOcservUsersPost(requestParameters.authorization, requestParameters.file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for backupOcservGroupsPost operation in SystemRestoreApi.
 * @export
 * @interface SystemRestoreApiBackupOcservGroupsPostRequest
 */
export interface SystemRestoreApiBackupOcservGroupsPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemRestoreApiBackupOcservGroupsPost
     */
    readonly authorization: string

    /**
     * JSON or JSON.GZ file
     * @type {File}
     * @memberof SystemRestoreApiBackupOcservGroupsPost
     */
    readonly file: File
}

/**
 * Request parameters for backupOcservUsersPost operation in SystemRestoreApi.
 * @export
 * @interface SystemRestoreApiBackupOcservUsersPostRequest
 */
export interface SystemRestoreApiBackupOcservUsersPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemRestoreApiBackupOcservUsersPost
     */
    readonly authorization: string

    /**
     * JSON or JSON.GZ file
     * @type {File}
     * @memberof SystemRestoreApiBackupOcservUsersPost
     */
    readonly file: File
}

/**
 * SystemRestoreApi - object-oriented interface
 * @export
 * @class SystemRestoreApi
 * @extends {BaseAPI}
 */
export class SystemRestoreApi extends BaseAPI {
    /**
     * Upload JSON or gzip-compressed (.json.gz) backup of ocserv groups
     * @summary Restore ocserv groups
     * @param {SystemRestoreApiBackupOcservGroupsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemRestoreApi
     */
    public backupOcservGroupsPost(requestParameters: SystemRestoreApiBackupOcservGroupsPostRequest, options?: RawAxiosRequestConfig) {
        return SystemRestoreApiFp(this.configuration).backupOcservGroupsPost(requestParameters.authorization, requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload JSON or gzip-compressed (.json.gz) backup of ocserv users
     * @summary Restore ocserv users
     * @param {SystemRestoreApiBackupOcservUsersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemRestoreApi
     */
    public backupOcservUsersPost(requestParameters: SystemRestoreApiBackupOcservUsersPostRequest, options?: RawAxiosRequestConfig) {
        return SystemRestoreApiFp(this.configuration).backupOcservUsersPost(requestParameters.authorization, requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }
}

