/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../core';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresPermissionDenied } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * SystemBackupApi - axios parameter creator
 * @export
 */
export const SystemBackupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Download gzip compressed JSON backup of all ocserv groups including default group configuration
         * @summary Backup ocserv groups
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservGroupsGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('backupOcservGroupsGet', 'authorization', authorization)
            const localVarPath = `/backup/ocserv_groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Download gzip compressed JSON backup of all ocserv users
         * @summary Backup ocserv users
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservUsersGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('backupOcservUsersGet', 'authorization', authorization)
            const localVarPath = `/backup/ocserv_users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemBackupApi - functional programming interface
 * @export
 */
export const SystemBackupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemBackupApiAxiosParamCreator(configuration)
    return {
        /**
         * Download gzip compressed JSON backup of all ocserv groups including default group configuration
         * @summary Backup ocserv groups
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async backupOcservGroupsGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.backupOcservGroupsGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemBackupApi.backupOcservGroupsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Download gzip compressed JSON backup of all ocserv users
         * @summary Backup ocserv users
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async backupOcservUsersGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.backupOcservUsersGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemBackupApi.backupOcservUsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemBackupApi - factory interface
 * @export
 */
export const SystemBackupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemBackupApiFp(configuration)
    return {
        /**
         * Download gzip compressed JSON backup of all ocserv groups including default group configuration
         * @summary Backup ocserv groups
         * @param {SystemBackupApiBackupOcservGroupsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservGroupsGet(requestParameters: SystemBackupApiBackupOcservGroupsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.backupOcservGroupsGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Download gzip compressed JSON backup of all ocserv users
         * @summary Backup ocserv users
         * @param {SystemBackupApiBackupOcservUsersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        backupOcservUsersGet(requestParameters: SystemBackupApiBackupOcservUsersGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.backupOcservUsersGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for backupOcservGroupsGet operation in SystemBackupApi.
 * @export
 * @interface SystemBackupApiBackupOcservGroupsGetRequest
 */
export interface SystemBackupApiBackupOcservGroupsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemBackupApiBackupOcservGroupsGet
     */
    readonly authorization: string
}

/**
 * Request parameters for backupOcservUsersGet operation in SystemBackupApi.
 * @export
 * @interface SystemBackupApiBackupOcservUsersGetRequest
 */
export interface SystemBackupApiBackupOcservUsersGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemBackupApiBackupOcservUsersGet
     */
    readonly authorization: string
}

/**
 * SystemBackupApi - object-oriented interface
 * @export
 * @class SystemBackupApi
 * @extends {BaseAPI}
 */
export class SystemBackupApi extends BaseAPI {
    /**
     * Download gzip compressed JSON backup of all ocserv groups including default group configuration
     * @summary Backup ocserv groups
     * @param {SystemBackupApiBackupOcservGroupsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemBackupApi
     */
    public backupOcservGroupsGet(requestParameters: SystemBackupApiBackupOcservGroupsGetRequest, options?: RawAxiosRequestConfig) {
        return SystemBackupApiFp(this.configuration).backupOcservGroupsGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Download gzip compressed JSON backup of all ocserv users
     * @summary Backup ocserv users
     * @param {SystemBackupApiBackupOcservUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemBackupApi
     */
    public backupOcservUsersGet(requestParameters: SystemBackupApiBackupOcservUsersGetRequest, options?: RawAxiosRequestConfig) {
        return SystemBackupApiFp(this.configuration).backupOcservUsersGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

