/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BackupRestoreResponse
 */
export interface BackupRestoreResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof BackupRestoreResponse
     */
    'existing'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BackupRestoreResponse
     */
    'inserted'?: Array<string>;
}

