/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HomeCPU } from './home-cpu';
// May contain unused imports in some cases
// @ts-ignore
import type { HomeRAM } from './home-ram';

/**
 * 
 * @export
 * @interface HomeDockerStats
 */
export interface HomeDockerStats {
    /**
     * 
     * @type {HomeCPU}
     * @memberof HomeDockerStats
     */
    'cpu'?: HomeCPU;
    /**
     * 
     * @type {string}
     * @memberof HomeDockerStats
     */
    'name': string;
    /**
     * 
     * @type {HomeRAM}
     * @memberof HomeDockerStats
     */
    'ram'?: HomeRAM;
}

