/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HomeDockerService } from '../models';
// @ts-ignore
import type { HomeGetHomeResponse } from '../models';
// @ts-ignore
import type { HomeOcservStatusResponse } from '../models';
// @ts-ignore
import type { HomeServerStatusResponse } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * HomeApi - axios parameter creator
 * @export
 */
export const HomeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Content of docker system usage stats (cpu, ram, swap)
         * @summary Content of docker system usage stats
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeContainerStatsGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('homeContainerStatsGet', 'authorization', authorization)
            const localVarPath = `/home/container-stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Content of home
         * @summary Content of home
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('homeGet', 'authorization', authorization)
            const localVarPath = `/home`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Content of ocserv server stats
         * @summary Content of ocserv server stats
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeOcservStatsGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('homeOcservStatsGet', 'authorization', authorization)
            const localVarPath = `/home/ocserv-stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Content of os system usage stats (cpu, ram, swap)
         * @summary Content of os system usage stats
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeSystemStatsGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('homeSystemStatsGet', 'authorization', authorization)
            const localVarPath = `/home/system-stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeApi - functional programming interface
 * @export
 */
export const HomeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HomeApiAxiosParamCreator(configuration)
    return {
        /**
         * Content of docker system usage stats (cpu, ram, swap)
         * @summary Content of docker system usage stats
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeContainerStatsGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<HomeDockerService>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeContainerStatsGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeApi.homeContainerStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Content of home
         * @summary Content of home
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeGetHomeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeApi.homeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Content of ocserv server stats
         * @summary Content of ocserv server stats
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeOcservStatsGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeOcservStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeOcservStatsGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeApi.homeOcservStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Content of os system usage stats (cpu, ram, swap)
         * @summary Content of os system usage stats
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeSystemStatsGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeServerStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeSystemStatsGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeApi.homeSystemStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HomeApi - factory interface
 * @export
 */
export const HomeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HomeApiFp(configuration)
    return {
        /**
         * Content of docker system usage stats (cpu, ram, swap)
         * @summary Content of docker system usage stats
         * @param {HomeApiHomeContainerStatsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeContainerStatsGet(requestParameters: HomeApiHomeContainerStatsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<HomeDockerService>> {
            return localVarFp.homeContainerStatsGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Content of home
         * @summary Content of home
         * @param {HomeApiHomeGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGet(requestParameters: HomeApiHomeGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<HomeGetHomeResponse> {
            return localVarFp.homeGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Content of ocserv server stats
         * @summary Content of ocserv server stats
         * @param {HomeApiHomeOcservStatsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeOcservStatsGet(requestParameters: HomeApiHomeOcservStatsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<HomeOcservStatusResponse> {
            return localVarFp.homeOcservStatsGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Content of os system usage stats (cpu, ram, swap)
         * @summary Content of os system usage stats
         * @param {HomeApiHomeSystemStatsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeSystemStatsGet(requestParameters: HomeApiHomeSystemStatsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<HomeServerStatusResponse> {
            return localVarFp.homeSystemStatsGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for homeContainerStatsGet operation in HomeApi.
 * @export
 * @interface HomeApiHomeContainerStatsGetRequest
 */
export interface HomeApiHomeContainerStatsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof HomeApiHomeContainerStatsGet
     */
    readonly authorization: string
}

/**
 * Request parameters for homeGet operation in HomeApi.
 * @export
 * @interface HomeApiHomeGetRequest
 */
export interface HomeApiHomeGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof HomeApiHomeGet
     */
    readonly authorization: string
}

/**
 * Request parameters for homeOcservStatsGet operation in HomeApi.
 * @export
 * @interface HomeApiHomeOcservStatsGetRequest
 */
export interface HomeApiHomeOcservStatsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof HomeApiHomeOcservStatsGet
     */
    readonly authorization: string
}

/**
 * Request parameters for homeSystemStatsGet operation in HomeApi.
 * @export
 * @interface HomeApiHomeSystemStatsGetRequest
 */
export interface HomeApiHomeSystemStatsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof HomeApiHomeSystemStatsGet
     */
    readonly authorization: string
}

/**
 * HomeApi - object-oriented interface
 * @export
 * @class HomeApi
 * @extends {BaseAPI}
 */
export class HomeApi extends BaseAPI {
    /**
     * Content of docker system usage stats (cpu, ram, swap)
     * @summary Content of docker system usage stats
     * @param {HomeApiHomeContainerStatsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApi
     */
    public homeContainerStatsGet(requestParameters: HomeApiHomeContainerStatsGetRequest, options?: RawAxiosRequestConfig) {
        return HomeApiFp(this.configuration).homeContainerStatsGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Content of home
     * @summary Content of home
     * @param {HomeApiHomeGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApi
     */
    public homeGet(requestParameters: HomeApiHomeGetRequest, options?: RawAxiosRequestConfig) {
        return HomeApiFp(this.configuration).homeGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Content of ocserv server stats
     * @summary Content of ocserv server stats
     * @param {HomeApiHomeOcservStatsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApi
     */
    public homeOcservStatsGet(requestParameters: HomeApiHomeOcservStatsGetRequest, options?: RawAxiosRequestConfig) {
        return HomeApiFp(this.configuration).homeOcservStatsGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Content of os system usage stats (cpu, ram, swap)
     * @summary Content of os system usage stats
     * @param {HomeApiHomeSystemStatsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApi
     */
    public homeSystemStatsGet(requestParameters: HomeApiHomeSystemStatsGetRequest, options?: RawAxiosRequestConfig) {
        return HomeApiFp(this.configuration).homeSystemStatsGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

