/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    DUMMY_BASE_URL,
    assertParamExists,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    serializeDataIfNeeded,
    toPathString,
    createRequestFunction
} from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresPermissionDenied } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { ModelsUser } from '../models';
// @ts-ignore
import type { ModelsUsersLookup } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
// @ts-ignore
import type { SystemChangeUserPassword } from '../models';
// @ts-ignore
import type { SystemChangeUserPasswordBySelf } from '../models';
// @ts-ignore
import type { SystemCreateUserData } from '../models';
// @ts-ignore
import type { SystemCreateUserResponse } from '../models';
// @ts-ignore
import type { SystemLoginData } from '../models';
// @ts-ignore
import type { SystemUpdatePermissionData } from '../models';
// @ts-ignore
import type { SystemUserLoginResponse } from '../models';
// @ts-ignore
import type { SystemUsersResponse } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List of Admin or staff users
         * @summary List of Admin or staff users
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {UsersGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (
            authorization: string,
            page?: number,
            size?: number,
            order?: string,
            sort?: UsersGetSortEnum,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersGet', 'authorization', authorization);
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Admin users login with Google captcha(captcha site key required in get config api)
         * @summary Admin users login
         * @param {SystemLoginData} request login data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLoginPost: async (request: SystemLoginData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersLoginPost', 'request', request);
            const localVarPath = `/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * List of Users Lookup
         * @summary List of Users Lookup
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLookupGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersLookupGet', 'authorization', authorization);
            const localVarPath = `/users/lookup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Change user password by self
         * @summary Change user password by self
         * @param {string} authorization Bearer TOKEN
         * @param {SystemChangeUserPasswordBySelf} request user new password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPasswordPost: async (
            authorization: string,
            request: SystemChangeUserPasswordBySelf,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersPasswordPost', 'authorization', authorization);
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersPasswordPost', 'request', request);
            const localVarPath = `/users/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Create user Admin or simple
         * @summary Create user
         * @param {string} authorization Bearer TOKEN
         * @param {SystemCreateUserData} request create admin user or staff data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPost: async (
            authorization: string,
            request: SystemCreateUserData,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersPost', 'authorization', authorization);
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersPost', 'request', request);
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Get User Profile
         * @summary Get User Profile
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersProfileGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersProfileGet', 'authorization', authorization);
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Delete simple user
         * @summary Delete simple user
         * @param {string} uid User UID
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUidDelete: async (
            uid: string,
            authorization: string,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('usersUidDelete', 'uid', uid);
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersUidDelete', 'authorization', authorization);
            const localVarPath = `/users/{uid}`.replace(`{${'uid'}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Change user password by admin
         * @summary Change user password by admin
         * @param {string} uid User UID
         * @param {string} authorization Bearer TOKEN
         * @param {SystemChangeUserPassword} request user new password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUidPasswordPost: async (
            uid: string,
            authorization: string,
            request: SystemChangeUserPassword,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('usersUidPasswordPost', 'uid', uid);
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersUidPasswordPost', 'authorization', authorization);
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersUidPasswordPost', 'request', request);
            const localVarPath = `/users/{uid}/password`.replace(`{${'uid'}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Update staff user permission
         * @summary Update staff user permission
         * @param {string} authorization Bearer TOKEN
         * @param {string} uid User UID
         * @param {SystemUpdatePermissionData} request staff user permission data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUidPermissionsPatch: async (
            authorization: string,
            uid: string,
            request: SystemUpdatePermissionData,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('usersUidPermissionsPatch', 'authorization', authorization);
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('usersUidPermissionsPatch', 'uid', uid);
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersUidPermissionsPatch', 'request', request);
            const localVarPath = `/users/{uid}/permissions`.replace(`{${'uid'}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        }
    };
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration);
    return {
        /**
         * List of Admin or staff users
         * @summary List of Admin or staff users
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {UsersGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(
            authorization: string,
            page?: number,
            size?: number,
            order?: string,
            sort?: UsersGetSortEnum,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemUsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(
                authorization,
                page,
                size,
                order,
                sort,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Admin users login with Google captcha(captcha site key required in get config api)
         * @summary Admin users login
         * @param {SystemLoginData} request login data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersLoginPost(
            request: SystemLoginData,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemUserLoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersLoginPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List of Users Lookup
         * @summary List of Users Lookup
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersLookupGet(
            authorization: string,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsUsersLookup>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersLookupGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersLookupGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Change user password by self
         * @summary Change user password by self
         * @param {string} authorization Bearer TOKEN
         * @param {SystemChangeUserPasswordBySelf} request user new password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersPasswordPost(
            authorization: string,
            request: SystemChangeUserPasswordBySelf,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemUsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersPasswordPost(authorization, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersPasswordPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create user Admin or simple
         * @summary Create user
         * @param {string} authorization Bearer TOKEN
         * @param {SystemCreateUserData} request create admin user or staff data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersPost(
            authorization: string,
            request: SystemCreateUserData,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemCreateUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersPost(authorization, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get User Profile
         * @summary Get User Profile
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersProfileGet(
            authorization: string,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersProfileGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersProfileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete simple user
         * @summary Delete simple user
         * @param {string} uid User UID
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUidDelete(
            uid: string,
            authorization: string,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUidDelete(uid, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersUidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Change user password by admin
         * @summary Change user password by admin
         * @param {string} uid User UID
         * @param {string} authorization Bearer TOKEN
         * @param {SystemChangeUserPassword} request user new password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUidPasswordPost(
            uid: string,
            authorization: string,
            request: SystemChangeUserPassword,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemUsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUidPasswordPost(
                uid,
                authorization,
                request,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersUidPasswordPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update staff user permission
         * @summary Update staff user permission
         * @param {string} authorization Bearer TOKEN
         * @param {string} uid User UID
         * @param {SystemUpdatePermissionData} request staff user permission data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUidPermissionsPatch(
            authorization: string,
            uid: string,
            request: SystemUpdatePermissionData,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUidPermissionsPatch(
                authorization,
                uid,
                request,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['UsersApi.usersUidPermissionsPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        }
    };
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration);
    return {
        /**
         * List of Admin or staff users
         * @summary List of Admin or staff users
         * @param {UsersApiUsersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(
            requestParameters: UsersApiUsersGetRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<SystemUsersResponse> {
            return localVarFp
                .usersGet(
                    requestParameters.authorization,
                    requestParameters.page,
                    requestParameters.size,
                    requestParameters.order,
                    requestParameters.sort,
                    options
                )
                .then((request) => request(axios, basePath));
        },
        /**
         * Admin users login with Google captcha(captcha site key required in get config api)
         * @summary Admin users login
         * @param {UsersApiUsersLoginPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLoginPost(
            requestParameters: UsersApiUsersLoginPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<SystemUserLoginResponse> {
            return localVarFp
                .usersLoginPost(requestParameters.request, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * List of Users Lookup
         * @summary List of Users Lookup
         * @param {UsersApiUsersLookupGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLookupGet(
            requestParameters: UsersApiUsersLookupGetRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<Array<ModelsUsersLookup>> {
            return localVarFp
                .usersLookupGet(requestParameters.authorization, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Change user password by self
         * @summary Change user password by self
         * @param {UsersApiUsersPasswordPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPasswordPost(
            requestParameters: UsersApiUsersPasswordPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<SystemUsersResponse> {
            return localVarFp
                .usersPasswordPost(requestParameters.authorization, requestParameters.request, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Create user Admin or simple
         * @summary Create user
         * @param {UsersApiUsersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPost(
            requestParameters: UsersApiUsersPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<SystemCreateUserResponse> {
            return localVarFp
                .usersPost(requestParameters.authorization, requestParameters.request, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Get User Profile
         * @summary Get User Profile
         * @param {UsersApiUsersProfileGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersProfileGet(
            requestParameters: UsersApiUsersProfileGetRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<ModelsUser> {
            return localVarFp
                .usersProfileGet(requestParameters.authorization, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Delete simple user
         * @summary Delete simple user
         * @param {UsersApiUsersUidDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUidDelete(
            requestParameters: UsersApiUsersUidDeleteRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .usersUidDelete(requestParameters.uid, requestParameters.authorization, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Change user password by admin
         * @summary Change user password by admin
         * @param {UsersApiUsersUidPasswordPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUidPasswordPost(
            requestParameters: UsersApiUsersUidPasswordPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<SystemUsersResponse> {
            return localVarFp
                .usersUidPasswordPost(
                    requestParameters.uid,
                    requestParameters.authorization,
                    requestParameters.request,
                    options
                )
                .then((request) => request(axios, basePath));
        },
        /**
         * Update staff user permission
         * @summary Update staff user permission
         * @param {UsersApiUsersUidPermissionsPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUidPermissionsPatch(
            requestParameters: UsersApiUsersUidPermissionsPatchRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .usersUidPermissionsPatch(
                    requestParameters.authorization,
                    requestParameters.uid,
                    requestParameters.request,
                    options
                )
                .then((request) => request(axios, basePath));
        }
    };
};

/**
 * Request parameters for usersGet operation in UsersApi.
 * @export
 * @interface UsersApiUsersGetRequest
 */
export interface UsersApiUsersGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersGet
     */
    readonly authorization: string;

    /**
     * Page number, starting from 1
     * @type {number}
     * @memberof UsersApiUsersGet
     */
    readonly page?: number;

    /**
     * Number of items per page
     * @type {number}
     * @memberof UsersApiUsersGet
     */
    readonly size?: number;

    /**
     * Field to order by
     * @type {string}
     * @memberof UsersApiUsersGet
     */
    readonly order?: string;

    /**
     * Sort order, either ASC or DESC
     * @type {'ASC' | 'DESC'}
     * @memberof UsersApiUsersGet
     */
    readonly sort?: UsersGetSortEnum;
}

/**
 * Request parameters for usersLoginPost operation in UsersApi.
 * @export
 * @interface UsersApiUsersLoginPostRequest
 */
export interface UsersApiUsersLoginPostRequest {
    /**
     * login data
     * @type {SystemLoginData}
     * @memberof UsersApiUsersLoginPost
     */
    readonly request: SystemLoginData;
}

/**
 * Request parameters for usersLookupGet operation in UsersApi.
 * @export
 * @interface UsersApiUsersLookupGetRequest
 */
export interface UsersApiUsersLookupGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersLookupGet
     */
    readonly authorization: string;
}

/**
 * Request parameters for usersPasswordPost operation in UsersApi.
 * @export
 * @interface UsersApiUsersPasswordPostRequest
 */
export interface UsersApiUsersPasswordPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersPasswordPost
     */
    readonly authorization: string;

    /**
     * user new password
     * @type {SystemChangeUserPasswordBySelf}
     * @memberof UsersApiUsersPasswordPost
     */
    readonly request: SystemChangeUserPasswordBySelf;
}

/**
 * Request parameters for usersPost operation in UsersApi.
 * @export
 * @interface UsersApiUsersPostRequest
 */
export interface UsersApiUsersPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersPost
     */
    readonly authorization: string;

    /**
     * create admin user or staff data
     * @type {SystemCreateUserData}
     * @memberof UsersApiUsersPost
     */
    readonly request: SystemCreateUserData;
}

/**
 * Request parameters for usersProfileGet operation in UsersApi.
 * @export
 * @interface UsersApiUsersProfileGetRequest
 */
export interface UsersApiUsersProfileGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersProfileGet
     */
    readonly authorization: string;
}

/**
 * Request parameters for usersUidDelete operation in UsersApi.
 * @export
 * @interface UsersApiUsersUidDeleteRequest
 */
export interface UsersApiUsersUidDeleteRequest {
    /**
     * User UID
     * @type {string}
     * @memberof UsersApiUsersUidDelete
     */
    readonly uid: string;

    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersUidDelete
     */
    readonly authorization: string;
}

/**
 * Request parameters for usersUidPasswordPost operation in UsersApi.
 * @export
 * @interface UsersApiUsersUidPasswordPostRequest
 */
export interface UsersApiUsersUidPasswordPostRequest {
    /**
     * User UID
     * @type {string}
     * @memberof UsersApiUsersUidPasswordPost
     */
    readonly uid: string;

    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersUidPasswordPost
     */
    readonly authorization: string;

    /**
     * user new password
     * @type {SystemChangeUserPassword}
     * @memberof UsersApiUsersUidPasswordPost
     */
    readonly request: SystemChangeUserPassword;
}

/**
 * Request parameters for usersUidPermissionsPatch operation in UsersApi.
 * @export
 * @interface UsersApiUsersUidPermissionsPatchRequest
 */
export interface UsersApiUsersUidPermissionsPatchRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof UsersApiUsersUidPermissionsPatch
     */
    readonly authorization: string;

    /**
     * User UID
     * @type {string}
     * @memberof UsersApiUsersUidPermissionsPatch
     */
    readonly uid: string;

    /**
     * staff user permission data
     * @type {SystemUpdatePermissionData}
     * @memberof UsersApiUsersUidPermissionsPatch
     */
    readonly request: SystemUpdatePermissionData;
}

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * List of Admin or staff users
     * @summary List of Admin or staff users
     * @param {UsersApiUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersGet(requestParameters: UsersApiUsersGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersGet(
                requestParameters.authorization,
                requestParameters.page,
                requestParameters.size,
                requestParameters.order,
                requestParameters.sort,
                options
            )
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Admin users login with Google captcha(captcha site key required in get config api)
     * @summary Admin users login
     * @param {UsersApiUsersLoginPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersLoginPost(requestParameters: UsersApiUsersLoginPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersLoginPost(requestParameters.request, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * List of Users Lookup
     * @summary List of Users Lookup
     * @param {UsersApiUsersLookupGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersLookupGet(requestParameters: UsersApiUsersLookupGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersLookupGet(requestParameters.authorization, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Change user password by self
     * @summary Change user password by self
     * @param {UsersApiUsersPasswordPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersPasswordPost(requestParameters: UsersApiUsersPasswordPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersPasswordPost(requestParameters.authorization, requestParameters.request, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create user Admin or simple
     * @summary Create user
     * @param {UsersApiUsersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersPost(requestParameters: UsersApiUsersPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersPost(requestParameters.authorization, requestParameters.request, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get User Profile
     * @summary Get User Profile
     * @param {UsersApiUsersProfileGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersProfileGet(requestParameters: UsersApiUsersProfileGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersProfileGet(requestParameters.authorization, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete simple user
     * @summary Delete simple user
     * @param {UsersApiUsersUidDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersUidDelete(requestParameters: UsersApiUsersUidDeleteRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersUidDelete(requestParameters.uid, requestParameters.authorization, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Change user password by admin
     * @summary Change user password by admin
     * @param {UsersApiUsersUidPasswordPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersUidPasswordPost(requestParameters: UsersApiUsersUidPasswordPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration)
            .usersUidPasswordPost(
                requestParameters.uid,
                requestParameters.authorization,
                requestParameters.request,
                options
            )
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update staff user permission
     * @summary Update staff user permission
     * @param {UsersApiUsersUidPermissionsPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersUidPermissionsPatch(
        requestParameters: UsersApiUsersUidPermissionsPatchRequest,
        options?: RawAxiosRequestConfig
    ) {
        return UsersApiFp(this.configuration)
            .usersUidPermissionsPatch(
                requestParameters.authorization,
                requestParameters.uid,
                requestParameters.request,
                options
            )
            .then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const UsersGetSortEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
} as const;
export type UsersGetSortEnum = (typeof UsersGetSortEnum)[keyof typeof UsersGetSortEnum];
