/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HomeCurrentStats } from './home-current-stats';
// May contain unused imports in some cases
// @ts-ignore
import type { HomeGeneralInfo } from './home-general-info';

/**
 * 
 * @export
 * @interface HomeOcservStatusResponse
 */
export interface HomeOcservStatusResponse {
    /**
     * 
     * @type {HomeCurrentStats}
     * @memberof HomeOcservStatusResponse
     */
    'current_stats'?: HomeCurrentStats;
    /**
     * 
     * @type {HomeGeneralInfo}
     * @memberof HomeOcservStatusResponse
     */
    'general_info'?: HomeGeneralInfo;
}

