/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HomeServerStatusResponseRam
 */
export interface HomeServerStatusResponseRam {
    /**
     * 
     * @type {number}
     * @memberof HomeServerStatusResponseRam
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeServerStatusResponseRam
     */
    'used'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeServerStatusResponseRam
     */
    'used_percent'?: number;
}

