/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ModelsUserRole } from './models-user-role';

/**
 *
 * @export
 * @interface ModelsUser
 */
export interface ModelsUser {
    /**
     * Hierarchy
     * @type {number}
     * @memberof ModelsUser
     */
    admin_id?: number;
    /**
     *
     * @type {string}
     * @memberof ModelsUser
     */
    created_at?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsUser
     */
    last_login: string;
    /**
     *
     * @type {ModelsUserRole}
     * @memberof ModelsUser
     */
    role?: ModelsUserRole;
    /**
     *
     * @type {Array<ModelsUser>}
     * @memberof ModelsUser
     */
    staff?: Array<ModelsUser>;
    /**
     *
     * @type {string}
     * @memberof ModelsUser
     */
    uid: string;
    /**
     *
     * @type {string}
     * @memberof ModelsUser
     */
    updated_at?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsUser
     */
    username: string;
}
