/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export const ModelsUserRole = {
    RoleSuperAdmin: 'super-admin',
    RoleAdmin: 'admin',
    RoleStaff: 'staff'
} as const;

export type ModelsUserRole = (typeof ModelsUserRole)[keyof typeof ModelsUserRole];
