/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ModelsUserRole } from './models-user-role';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemPermissionData } from './system-permission-data';

/**
 *
 * @export
 * @interface SystemCreateUserData
 */
export interface SystemCreateUserData {
    /**
     *
     * @type {number}
     * @memberof SystemCreateUserData
     */
    admin_id?: number;
    /**
     *
     * @type {string}
     * @memberof SystemCreateUserData
     */
    password: string;
    /**
     *
     * @type {Array<SystemPermissionData>}
     * @memberof SystemCreateUserData
     */
    permissions?: Array<SystemPermissionData>;
    /**
     *
     * @type {ModelsUserRole}
     * @memberof SystemCreateUserData
     */
    role?: ModelsUserRole;
    /**
     *
     * @type {string}
     * @memberof SystemCreateUserData
     */
    username: string;
}
