/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ModelsUserAction } from './models-user-action';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsUserService } from './models-user-service';

/**
 *
 * @export
 * @interface SystemPermissionData
 */
export interface SystemPermissionData {
    /**
     *
     * @type {ModelsUserAction}
     * @memberof SystemPermissionData
     */
    action: ModelsUserAction;
    /**
     *
     * @type {ModelsUserService}
     * @memberof SystemPermissionData
     */
    service: ModelsUserService;
}
