/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsUserRole } from './models-user-role';
// May contain unused imports in some cases
// @ts-ignore
import type { UsersPermissionData } from './users-permission-data';

/**
 * 
 * @export
 * @interface UsersCreateUserData
 */
export interface UsersCreateUserData {
    /**
     * 
     * @type {number}
     * @memberof UsersCreateUserData
     */
    'admin_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersCreateUserData
     */
    'password': string;
    /**
     * 
     * @type {Array<UsersPermissionData>}
     * @memberof UsersCreateUserData
     */
    'permissions'?: Array<UsersPermissionData>;
    /**
     * 
     * @type {ModelsUserRole}
     * @memberof UsersCreateUserData
     */
    'role'?: ModelsUserRole;
    /**
     * 
     * @type {string}
     * @memberof UsersCreateUserData
     */
    'username': string;
}



